import "server-only";
import { Types, type ClientSession } from "mongoose";
import { connectToDatabase } from "@/server/db/mongoose";
import { FeedUploadModel } from "@/server/models/feed-upload";

export type FeedRecord = { id: string; sellerId: string; uploadedByUserId: string; fileName: string; storageObjectKey: string; fileType: "CSV"; feedType: "PRODUCT_LISTING"; checksum: string; fileSizeBytes: number; mappingVersion: "catalog-map/v1"; processingStatus: "PENDING" | "DISPATCHING" | "PROCESSING" | "COMPLETED" | "FAILED"; dispatchState: "PENDING" | "ACCEPTED" | "FAILED"; jobId: string; idempotencyKey: string; correlationId: string; totalRows: number | null; processedRows: number; acceptedRows: number; rejectedRows: number; uploadedAt: Date; processedAt: Date | null; };
const projection = "+storageObjectKey +idempotencyKey";
type PersistedFeed = Omit<FeedRecord, "id" | "sellerId" | "uploadedByUserId"> & { _id: Types.ObjectId; sellerId: Types.ObjectId; uploadedByUserId: Types.ObjectId };
function shape(value: unknown): FeedRecord { const row = value as PersistedFeed; return { id: row._id.toString(), sellerId: row.sellerId.toString(), uploadedByUserId: row.uploadedByUserId.toString(), fileName: row.fileName, storageObjectKey: row.storageObjectKey, fileType: row.fileType, feedType: row.feedType, checksum: row.checksum, fileSizeBytes: row.fileSizeBytes, mappingVersion: row.mappingVersion, processingStatus: row.processingStatus, dispatchState: row.dispatchState, jobId: row.jobId, idempotencyKey: row.idempotencyKey, correlationId: row.correlationId, totalRows: row.totalRows, processedRows: row.processedRows, acceptedRows: row.acceptedRows, rejectedRows: row.rejectedRows, uploadedAt: row.uploadedAt, processedAt: row.processedAt }; }
export class FeedUploadRepository {
  async create(input: Omit<FeedRecord, "id" | "uploadedAt" | "processedAt" | "totalRows" | "processedRows" | "acceptedRows" | "rejectedRows">, session: ClientSession): Promise<FeedRecord> { await connectToDatabase(); const created = await FeedUploadModel.create([{ ...input, sellerId: new Types.ObjectId(input.sellerId), uploadedByUserId: new Types.ObjectId(input.uploadedByUserId), totalRows: null, processedRows: 0, acceptedRows: 0, rejectedRows: 0, processedAt: null } as never], { session }); return shape(created[0]); }
  async getScoped(id: string, sellerId: string): Promise<FeedRecord | null> { await connectToDatabase(); if (!Types.ObjectId.isValid(id) || !Types.ObjectId.isValid(sellerId)) return null; const item = await FeedUploadModel.findOne({ _id: id, sellerId }).select(projection).lean().exec(); return item ? shape(item) : null; }
  async listScoped(sellerId: string, cursor?: string, limit = 25): Promise<FeedRecord[]> { await connectToDatabase(); const query: { sellerId: Types.ObjectId; _id?: { $lt: Types.ObjectId } } = { sellerId: new Types.ObjectId(sellerId) }; if (cursor && Types.ObjectId.isValid(cursor)) query._id = { $lt: new Types.ObjectId(cursor) }; const rows = await FeedUploadModel.find(query as never).sort({ uploadedAt: -1, _id: -1 }).limit(limit).select(projection).lean().exec(); return rows.map(shape); }
  async markDispatch(id: string, state: "ACCEPTED" | "FAILED"): Promise<void> { await connectToDatabase(); await FeedUploadModel.updateOne({ _id: id, dispatchState: "PENDING" }, { $set: { dispatchState: state, processingStatus: state === "ACCEPTED" ? "PROCESSING" : "FAILED" } }).exec(); }
  async applyCallback(input: { jobId: string; sellerId: string; feedUploadId: string; checksum: string; idempotencyKey: string; outcome: "COMPLETED" | "FAILED" | "CANCELLED"; totalRows: number; processedRows: number; acceptedRows: number; rejectedRows: number; session: ClientSession }): Promise<FeedRecord | null> { await connectToDatabase(); const row = await FeedUploadModel.findOneAndUpdate({ _id: input.feedUploadId, sellerId: input.sellerId, jobId: input.jobId, checksum: input.checksum, idempotencyKey: input.idempotencyKey }, { $set: { processingStatus: input.outcome === "COMPLETED" ? "COMPLETED" : "FAILED", totalRows: input.totalRows, processedRows: input.processedRows, acceptedRows: input.acceptedRows, rejectedRows: input.rejectedRows, processedAt: new Date() } }, { new: true, session: input.session }).select(projection).lean().exec(); return row ? shape(row) : null; }
}
export const feedUploadRepository = new FeedUploadRepository();
