"use client";
/* eslint-disable react-hooks/set-state-in-effect -- state changes occur after the asynchronous API request resolves. */
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/Button";
import { EmptyState, ErrorState, Skeleton } from "@/components/ui/Cards";
import { StatusBadge } from "@/components/ui/StatusBadge";
import { feedListResponseSchema, type FeedDetail } from "@/lib/contracts/feeds";

type Feed = Omit<FeedDetail, "jobId" | "dispatchState" | "sourceIntegrity" | "timeline">;
function badge(status: Feed["processingStatus"]) { return status === "COMPLETED" ? "ready" : status === "FAILED" ? "blocked" : "system" as const; }
export function FeedHistoryClient() { const router = useRouter(); const [feeds, setFeeds] = useState<Feed[] | null>(null); const [error, setError] = useState<string | null>(null); const [query, setQuery] = useState(""); const load = async () => { try { const response = await fetch("/api/feeds", { cache: "no-store" }); if (!response.ok) throw new Error("Your feed history could not be loaded."); setFeeds(feedListResponseSchema.parse(await response.json()).data); setError(null); } catch (cause) { setError(cause instanceof Error ? cause.message : "Your feed history could not be loaded."); } }; useEffect(() => { void load(); }, []); const visible = useMemo(() => (feeds ?? []).filter((feed) => feed.fileName.toLowerCase().includes(query.toLowerCase()) || feed.id.includes(query)), [feeds, query]); if (error) return <ErrorState title="Feed history is unavailable" description={error} onRetry={() => void load()} />; if (!feeds) return <div className="space-y-3"><Skeleton className="h-12 w-full" /><Skeleton className="h-12 w-full" /></div>; return <><div className="mb-5 flex items-center justify-between gap-3"><input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search file or feed ID" className="h-11 w-full max-w-md rounded-[10px] border border-[var(--cg-border-strong)] bg-white px-3.5 text-[13px] outline-none focus:border-[var(--cg-purple)]" /><Button onClick={() => router.push("/seller/feeds/upload")}>Upload feed</Button></div>{visible.length === 0 ? <EmptyState title={feeds.length ? "No feeds match your search" : "No feeds uploaded yet"} description="Upload a CSV product listing to start a private validation run." primaryAction={{ label: "Upload feed", onClick: () => router.push("/seller/feeds/upload") }} /> : <div className="overflow-hidden rounded-[12px] border border-[var(--cg-border)] bg-white"><table className="w-full text-left text-[13px]"><thead><tr className="border-b border-[var(--cg-border)] text-[11px] uppercase tracking-wide text-[var(--cg-text-muted)]"><th className="px-5 py-3">File</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Rows</th><th className="px-5 py-3">Uploaded</th></tr></thead><tbody>{visible.map((feed) => <tr key={feed.id} className="border-b border-[var(--cg-border)] last:border-0 hover:bg-[var(--cg-surface)]"><td className="px-5 py-3.5"><Link href={`/seller/feeds/${feed.id}`} className="font-semibold text-[var(--cg-purple)] hover:underline">{feed.fileName}</Link><p className="cg-mono mt-1 text-[11px] text-[var(--cg-text-muted)]">{feed.id}</p></td><td className="px-5 py-3.5"><StatusBadge tone={badge(feed.processingStatus)}>{feed.processingStatus}</StatusBadge></td><td className="px-5 py-3.5 text-[var(--cg-text-secondary)]">{feed.totalRows === null ? "Waiting for parser" : `${feed.processedRows} / ${feed.totalRows}`}</td><td className="px-5 py-3.5 text-[var(--cg-text-muted)]">{new Date(feed.uploadedAt).toLocaleString()}</td></tr>)}</tbody></table></div>}</>; }
