"use client";
import { useState } from "react";
import { Button } from "@/components/ui/Button";
import { Alert } from "@/components/ui/Cards";
import { useToast } from "@/components/ui/LiveRegion";
import type { AccessRequestSummary } from "@/lib/contracts/access-requests";
import { errorEnvelopeSchema } from "@/lib/contracts/errors";

export function AdminAccessRequests({ initialRequests }: { initialRequests: AccessRequestSummary[] }) {
  const [requests, setRequests] = useState<AccessRequestSummary[]>(initialRequests); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false); const { announce } = useToast();
  async function load() { setLoading(true); const response = await fetch("/api/admin/access-requests", { cache: "no-store" }).catch(() => null); if (!response?.ok) { setError("Access requests could not be loaded."); setLoading(false); return; } const payload = await response.json(); setRequests(payload.data); setLoading(false); }
  async function decide(id: string, decision: "approve" | "revoke") { setError(null); const verb = decision === "approve" ? "approve" : "revoke"; const reason = window.prompt(`${decision === "approve" ? "Approval" : "Revocation"} note (optional — leave blank to skip):`); if (reason === null) return; const response = await fetch(`/api/admin/access-requests/${id}/${decision}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(reason.trim() ? { reason } : {}) }); if (!response.ok) { const parsed = errorEnvelopeSchema.safeParse(await response.json().catch(() => null)); setError(parsed.success ? `Could not ${verb} this request: ${parsed.data.error.message}` : `Could not ${verb} this request. Please try again.`); return; } announce(`Access request ${decision === "approve" ? "approved" : "revoked"}.`, "success"); await load(); }
  async function dismiss(id: string) { setError(null); const response = await fetch(`/api/admin/access-requests/${id}/dismiss`, { method: "POST", headers: { "content-type": "application/json" }, body: "{}" }); if (!response.ok) { const parsed = errorEnvelopeSchema.safeParse(await response.json().catch(() => null)); setError(parsed.success ? `Could not dismiss this request: ${parsed.data.error.message}` : "Could not dismiss this request. Please try again."); return; } setRequests((current) => current.filter((request) => request.id !== id)); announce("Access request dismissed from your view.", "success"); }
  if (loading) return <p className="text-[13px] text-[var(--cg-text-muted)]">Refreshing access requests…</p>;
  return <div className="flex flex-col gap-4">{error ? <Alert tone="danger" title="Request operation failed">{error}</Alert> : null}{requests.length === 0 ? <Alert title="No access requests">New seller and reviewer proposals will appear here.</Alert> : requests.map((request) => <article key={request.id} className="rounded-[12px] border border-[var(--cg-border)] bg-white p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-[14px] font-semibold">{request.fullName}</p><p className="text-[12.5px] text-[var(--cg-text-muted)]">{request.email} · {request.role === "SELLER_OPERATOR" ? request.businessName ?? "Seller" : "Reviewer"}</p></div><span className="rounded-full bg-[var(--cg-purple-soft)] px-2.5 py-1 text-[11px] font-semibold text-[var(--cg-purple)]">{request.status}</span></div><p className="mt-3 max-w-3xl text-[13px] text-[var(--cg-text-secondary)]">{request.proposal}</p>{request.status === "PENDING" ? <div className="mt-4 flex gap-2"><Button onClick={() => void decide(request.id, "approve")}>Approve</Button><Button variant="destructive" onClick={() => void decide(request.id, "revoke")}>Revoke</Button></div> : <div className="mt-3 flex items-center justify-between gap-3"><p className="text-[12px] text-[var(--cg-text-muted)]">{request.decisionReason ?? "No decision note."}</p><Button variant="secondary" onClick={() => void dismiss(request.id)}>Dismiss</Button></div>}</article>)}</div>;
}
